dataset: dbpedia
end_model_lr: 1e-4
h_sizes:
- 768
- 256
- 64
- 4
max_num: 250000
model_path: ../models/dbpedia/
preds_path: ../results/dbpedia/
results_path: ../results/dbpedia/
target_0: company
target_1: school, university
target_2: artist
target_3: athlete
target_4: politics 
target_5: transportation
target_6: building, tower
target_7: river, mountain, lake
target_8: village
target_9: animal
target_10: plant, tree
target_11: album
target_12: film
target_13: novel, publication, book
