activation: torch.nn.LeakyReLU()
average: weighted
base_encoder: all-mpnet-base-v2
batch_size: 128
criterion: torch.nn.CrossEntropyLoss(reduction='none')
data_path: /zfsauton/project/public/chufang/classes/
dataset: imdb
device: cuda
epochs: 200
h_sizes:
- 768
- 256
- 64
- 2
label_model_lr: 0.01
label_model_n_epochs: 100
lr: 1e-3
max_num: 7000
min_df: 0.001
model_path: ../models/imdb/
n_bootstrap: 100
n_jobs: 10
ngram_range: !!python/tuple
- 1
- 3
normalize_embeddings: false
patience: 3
preds_path: ../results/imdb/
results_path: ../results/imdb/
show_progress_bar: true
target_negative: negative, hate, expensive, bad, poor, broke, waste, horrible, would
  not recommend
target_positive: good, positive, excellent, amazing, love, fine, good quality, would
  recommend
topk: 300
use_noise_aware_loss: true
weight_decay: 1e-4
