base_encoder: all-mpnet-base-v2
data_path: /zfsauton/project/public/chufang/classes/
dataset: imdb
label_model_lr: 0.01
label_model_n_epochs: 100
min_df: 0.001
ngram_range: !!python/tuple
- 1
- 3
save_LM_preds_path: ../results/imdb/
target_negative: negative, hate, expensive, bad, poor, broke, waste, horrible, would
  not recommend
target_positive: good, positive, excellent, amazing, love, fine, good quality, would
  recommend
topk: 300
